active_directory:
  root: "<ldap-root>"
  filter: "<customized-filter>"
  url: "<ad-url>"
  domain: "<domain>"
secure_endpoints: "<secure endpoints>"
admin_accounts: "<superuser-accounts>"

spring:
  r2dbc:
    url: "r2dbc:<protocol>://<url>:<port>"
    name: "<database>"
    username: "<username>"
    password: "<password>"
    pool:
      max-size: <max-pool-size>
      initial-size: <initial-pool-size>

jjwt:
  secret: <jwt-secret>
  expiration: <jwt-expirationtime>
